apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContosoOnlineOrders.Api
  labels:
    app: ContosoOnlineOrders
spec:
  replicas: 2
  selector:
    matchLabels:
      service: ContosoOnlineOrders.Api
  template:
    metadata:
      labels:
        app: weather-forecast
        service: ContosoOnlineOrders.Api
    spec:
      containers:
        - name: ContosoOnlineOrders.Api
          image: acrdemprepo.azurecr.io/fshomou/ContosoOnlineOrders.Api:v#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: ContosoOnlineOrders.Api
  labels:
    app: weather-forecast
    service: ContosoOnlineOrders.Api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http 
  selector:
    service: ContosoOnlineOrders.Api