apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosoapi
  labels:
    app: ContosoOnlineOrders
spec:
  replicas: 2
  selector:
    matchLabels:
      service: contosoapi
  template:
    metadata:
      labels:
        app: ContosoOnlineOrders
        service: contosoapi
    spec:
      containers:
        - name: contosoapi
          image: acrdemprepo.azurecr.io/fshomou/contosoonlineorders:v#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: contosoapi
  labels:
    app: ContosoOnlineOrders
    service: contosoapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http 
  selector:
    service: contosoapi
