apiVersion: apps/v1
kind: Deployment
metadata:
  name: ContosoOnlineOrdersApi
  labels:
    app: ContosoOnlineOrders
spec:
  replicas: 2
  selector:
    matchLabels:
      service: ContosoOnlineOrdersApi
  template:
    metadata:
      labels:
        app: ContosoOnlineOrders
        service: ContosoOnlineOrders.Api
    spec:
      containers:
        - name: ContosoOnlineOrdersApi
          image: acrdemprepo.azurecr.io/fshomou/ContosoOnlineOrdersApi:v#{Build.BuildId}#
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: ContosoOnlineOrdersApi
  labels:
    app: ContosoOnlineOrders
    service: ContosoOnlineOrdersApi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http 
  selector:
    service: ContosoOnlineOrdersApi
